### ISSUE TITLE
File descriptors don't seemed to be closed after deletion

### ISSUE THREAD

**Issue by danathesane** [circus-tent/chaussette#76]
Hello,
I'm using chaussette v1.3.0 (with circus) to host a pyramid web service that accepts large posts (32MB) and writes the body to a file. I'm using the --fd option.

After several requests, disk usage grows (until the volume is full) in proportion to the data POST'ed and lsof has many entries like the following for the chaussette process(es):

> chaussett  <pid>      <username>   26u      REG              253,0 46789038      35843 /tmp/tmp2563Z5 (deleted)
> chaussett  <pid>      <username>   27u      REG              253,0 46724414      49294 /tmp/tmpunH04b (deleted)
> chaussett  <pid>      <username>   28u      REG              253,0     4096      34605 /tmp/ffiv6K58f (deleted)
> chaussett  <pid>      <username>   29u      REG              253,0 46720826      35846 /tmp/tmpJzDbF4 (deleted)
> chaussett  <pid>      <username>   30u      REG              253,0 46749554      50229 /tmp/tmpwEM6dV (deleted)
> chaussett  <pid>      <username>   31u      REG              253,0 46760578      50230 /tmp/tmpoetYVY (deleted)
> chaussett  <pid>      <username>   32u      REG              253,0 46737552      50236 /tmp/tmpLw0pQW (deleted)
> chaussett  <pid>      <username>   33u      REG              253,0 46743846      55518 /tmp/tmpEQQDMM (deleted)
> chaussett  <pid>      <username>   34u      REG              253,0 46759294      50237 /tmp/tmpJtagy5 (deleted)
> chaussett  <pid>      <username>   35u      REG              253,0 46792302      63710 /tmp/tmpz_Fw9m (deleted)
> chaussett  <pid>      <username>   36u      REG              253,0 46765054      63715 /tmp/tmpEgMn82 (deleted)
> chaussett  <pid>      <username>   37u      REG              253,0 46787903      63720 /tmp/tmp2ylD4e (deleted)
> chaussett  <pid>      <username>   38u      REG              253,0 46792459      63717 /tmp/tmpHBGzsZ (deleted)
> chaussett  <pid>      <username>   39u      REG              253,0 46794015      63726 /tmp/tmpXK8Ngv (deleted)
> chaussett  <pid>      <username>   40u      REG              253,0 46787845      63730 /tmp/tmpkoyBVZ (deleted)
> chaussett  <pid>      <username>   41u      REG              253,0 46741383      63732 /tmp/tmp476UoG (deleted)
> chaussett  <pid>      <username>   42u      REG              253,0 46802099      63733 /tmp/tmp0ukD2Q (deleted)
> chaussett  <pid>      <username>   43u      REG              253,0 46817047      63738 /tmp/tmpibzajV (deleted)
> chaussett  <pid>      <username>   44u      REG              253,0 46797917      63739 /tmp/tmpy9Xi0f (deleted)

Perhaps chaussette or circus deletes the tmp file without closing it?

When I restart my chaussette processes, disk usage goes back to normal. The waitress and gevent backends both had this behaviour, but not when I run the app directly with pserve.

Cheers.

**Comment by k4nar** [comment]
@danathesane : Did you intentionally close this issue ? :)

**Comment by danathesane** [comment]
Yes, I noticed that the issue occurs when pserve is used as well. I'll investigate further and re-open (or make a new issue) if appropriate.

**Comment by k4nar** [comment]
Ok thanks!
